# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3"
services:
  db:
    image: "postgres:9.6.5-alpine"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    env_file: ./config/.env

  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - django-static:/var/www/django/static
    depends_on:
      - db
    networks:
      - webnet
    env_file: ./config/.env
    environment:
      DJANGO_DATABASE_HOST: db

networks:
  webnet:

volumes:
  pgdata:
  django-static:
